DATABASE:
  DRIVER: postgres
  HOST: localhost
  PORT: 6432
  NAME: pismo
  USERNAME: pismo
  PASSWORD: "****"
  QUERY: sslmode=disable&timezone=UTC
SERVER:
  PORT: 8080
  READ_TIMEOUT_MS: 20000
  WRITE_TIMEOUT_MS: 15000
  GRACEFUL_SHUTDOWN_TIMEOUT_MS: 20000